### ISSUE TITLE
Plate bending solution using FEA in C#

### ISSUE THREAD

**Issue by upuri** [BriefFiniteElementNet/BriefFiniteElement.Net#105]
Description:
The finite element will be a four noded quadrilateral isoparametric element (Q4). Its local stiffness will have in-plane stiffness (plane stress with 2 dof at each node: ux and uy). And thick plate bending stiffness based on Mindlin theory (3 dof at each node: uz ,theta_x, theta_y). Thus the quadrilateral finite element will have 5 dof per node and its element stiffness will be 20*20. Please create one form (UI) to read input data, analyze and plot results. Programming language is C#

Steps:
Read the model data from an input file
Formulate inplane stiffness for an element (plane stress)
Formulate thick plate bending stiffness using Mindlin theory
Combine step 2 and step 3 to form a local stiffness (20*20 size)
Convert the local matrix in step 4 to form a shell element global stiffness matrix
Assemble matrix for the whole model to get [K]
Find the force vector {P}
Solve [K] {u} ={P}
Find the global displacement {u}
Calculate plate local force (Mx, My Mxy, Qx, Qy) per unit length and global nodal force (R, MX, MY), displacement, plate stress and write into an output file.
Contour plot of Mxx, Myy Mxy, Qx, Qy and global displacement

**Comment by epsi1on** [comment]
Hi,
This project definition needs some basic knowledge about the FEM itself regardless of this library.
Well you need two formulations, first is the Q4 membrane element and second is the Mindlin plate bending behavior. This library does not have Mindlin plate bending, but another alternative formulation named DKQ (stands for Discrete Kirchoff Quadrilatural). To use this, you can use `QuadrilaturalElement` class located [here](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/master/BriefFiniteElementNet.CustomElements/Elements/QuadrilaturalElement.cs). Also calculation codes available [here](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.CustomElements/ElementHelpers).

ALSO NOTE THAT CODE IS NOT COMPLETELY VERIFIED YET, SO YOU MAY LOOSE TIME to learn a incomplete code.

Take a look at example here, which uses `TriangleElement` class:

https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.Validation/Case_01

`TriangleElement` results is tested and verified, if you allowed to use it instead of `QuadrilaturalElement` then things will be better. Again pls. note that Mindlin is not implemented yet, but Discrete Kirchoff is implemented.

Also about the steps, there are almost standard steps for a finite element software, Anyways this library does a little different steps with description available [here](https://bfenet.readthedocs.io/en/latest/miscellaneoustopics/solveprocedure.html)

**Comment by epsi1on** [comment]
> Most of the links are dead...

Hi,
There where some major file restructure, so files are massively moved (but not deleted)
you should search for each file again with search bar in top of page.
