### ISSUE TITLE
Error Matrix Must be Symmetric Positive Definite

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#129]
Hi eps1on,
I am trying to integrate a wall element into my structure and solve it with the BriefFiniteElement library, then it throws me the following error message "![errorInMatrix](https://user-images.githubusercontent.com/53960987/161441944-f6326281-1b5d-4d43-93a9-e5bf0c1c47eb.png)"

**Comment by epsi1on** [comment]
Hi,
The reason is that your model is not stable, and several reason can cause it. Most likely some DoFs are not connected to any element, neither are fixed to ground so they can freely move. To find such DoFs, take a look at here:
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/wiki/How-to-fix-NotPosDef-error

**Comment by MLiranzo** [comment]
Hi eps1on,
I have checked all the data of my example of a 3D structure with a wall element, I have not been able to determine the source of the error. I attach the example for a check.
[Example with wall.txt](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/8439182/Example.with.wall.txt)
Thank You.

**Comment by epsi1on** [comment]
ok, i'll close the issue
