### ISSUE TITLE
Bar Element Behavior and Analysis Results

### ISSUE THREAD

**Issue by BimwerxNZ** [BriefFiniteElementNet/BriefFiniteElement.Net#130]
Hi, great library and effort so far!

One question, when I build a frame structure consisting of only bar elements (columns; beams; and braces), I get weird results when comparing to 2 other FE Frame tools. 

When I use BarElementBehaviours.FullFrame for all elements, the shear forces, displacement and moments seems way off, but axial seems in ball-park.

When I change the beam elements (start- and end Zs are equal) to BarElementBehaviours.FullBeam, then I get more accurate displacement, Shear and Moments, but Axial is zero (for these beams). 

What is the correct way to model these elements? Also, would the behavior also control end-releases?

Here is the saved model for reference: [https://www.dropbox.com/s/rjah6il8ej9yxmv/test.bfe?dl=0](url)

Thanks in advance.

**Comment by epsi1on** [comment]
> One question, when I build a frame structure consisting of only bar elements (columns; beams; and braces), I get weird results when comparing to 2 other FE Frame tools.
> 
> When I use BarElementBehaviours.FullFrame for all elements, the shear forces, displacement and moments seems way off, but axial seems in ball-park.
> 
> When I change the beam elements (start- and end Zs are equal) to BarElementBehaviours.FullBeam, then I get more accurate displacement, Shear and Moments, but Axial is zero (for these beams).
> 
> What is the correct way to model these elements? 

I think a good way is to use ``FullFrame`` behavior for all elements, but you are saying that result is not consistent with other FE tools. So you must check other two reference tools and see what behavior are they using for the elements. this library have some validation, specially for BarElement which have almost zero error when compare to opensees for example. Also your case is a little different which have distributed load on elements, so it is a little challenging to validate with your reference tools. I can help you to the validation. What is reference software you are using? 

> Also, would the behavior also control end-releases?

For example if one uses `Truss` behavior for a very thick beam, then the bending of beam is not taken into account (even if it have a very large section inertia) so I think answer to this question must be yes rather than no.


> Here is the saved model for reference: [https://www.dropbox.com/s/rjah6il8ej9yxmv/test.bfe?dl=0](url)

I've checked it out

**Comment by BimwerxNZ** [comment]
Thank you for your response! I used Prokon's SUMO FEA modules for comparison, and also Frame 3DD. Both Prokon's SUMO and Frame 3DD yield similar results, but I'm struggling to get the same with BriefFinite.net. I suspect that SUMO uses a Timoshenko method for beams, and in my test model, all elements had fixed constraints - just to compare equally. Similar loads were used also.

Prokon: [https://www.prokon.com/](url) and SUMO: [https://www.prokon.com/structural-analysis/](url)

I've placed a detailed output report for you here: [https://www.dropbox.com/s/tn6jgcsj8uyn64u/BriefFinite%20Issues.docx?dl=0](url)

and source code (apologies, it's VB.Net) here: [https://www.dropbox.com/s/54s4ct7kwxwl8ra/FEA_Test_Brief.zip?dl=0](url)

I thought maybe I'm doing something wrong with units, but I've checked and re-checked.

Any guidance would be greatly appreciated.
Thanks in advance.

**Comment by epsi1on** [comment]
I suggest you to start with a small model, like a single level, single span frame with distributed load on the beam. so there will be 3 elements and four nodes and that will make the life easier. As i remember I did such validations and result are almost identical (very small relative error, like `1e-6`)
Also I suggest to compare bfe result with frame3dd first, if it is close enough then finally check with prokon's result. this is because frame3dd output is detailed, but i'm not familiar with the prokon.
I can help you on this issue for payment. I mean i'll help you to find out the reason which is making this discrepancy. And if it is BFE bug, then i'll turn your payment back. so please send me email if you are willing me to do it for you, otherwise we can continue with this issue.

Note1: note that it is possible than BFE have bugs itself, if you find any bug then let me know and i'll fix it (have a look at other issues by other users)

Note2: there is a class named ``Frame3DDValidator`` ([link](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/94b58f8ba54d029e4afcd2267b99e0e080c95533/BriefFiniteElementNet.Validation/Frame3ddValidator.cs)) which does the validation of any model with frame3dd. that is coded specially for comparing frame3dd output with BFE output. that can help you...

**Comment by epsi1on** [comment]
please reopen if still any problem
