### ISSUE TITLE
How to define constrains in local coordinate system?

### ISSUE THREAD

**Issue by Georgerdx** [BriefFiniteElementNet/BriefFiniteElement.Net#149]
Hello,

I just have a question about creating constraints.
I would like to create constraints in other than global coordinate system. Is that possible?

Example: I have a 3D beam which is not parallel to any axis of the global coordinate system. I would like to define X and Y direction relaxed and Z direction fixed in the direction of the beam. How would I define this in the code?

Thank you
Best regards
Juraj

**Comment by epsi1on** [comment]
I think what you mean is skewed support like the image below (node number 3)
Unfortunately, that is not implemented in the library...

![image](https://user-images.githubusercontent.com/7839141/198992897-07e548f0-0414-49ed-b322-3f7fae3451ba.png)

**Comment by epsi1on** [comment]
But you can get approx result with some tricks which can increase complexity of your code.
 for example use a strong truss element instead of skewed support like this (red element is perpendicular to skewed support axis). Also note that this solution is approx, also can increase the complexity of your code

![image](https://user-images.githubusercontent.com/7839141/198994224-ddff8281-5c84-4d14-92e3-b73c44a3d992.png)
this way

thanks

**Comment by epsi1on** [comment]
inactivity
