### ISSUE TITLE
Simply supported beam - simple example cant get internal forces

### ISSUE THREAD

**Issue by PedroArvy** [BriefFiniteElementNet/BriefFiniteElement.Net#18]
/*

               3 kN/m                           
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^              
     ----------------------------
    /\           10m             /\

    n1                         n2   
    
    */

    public void SimplySupportedBeamUDL()
    {
      var model = new BriefFiniteElementNet.Model();

      var pin = new Constraint(
        dx: DofConstraint.Fixed, dy: DofConstraint.Fixed, dz: DofConstraint.Fixed, 
        rx: DofConstraint.Fixed, ry: DofConstraint.Released, rz: DofConstraint.Fixed);

      Node n1, n2;

      model.Nodes.Add(n1 = new Node(x: 0.0, y: 0.0, z: 0.0) { Constraints = pin });
      model.Nodes.Add(n2 = new Node(x: 10000.0, y: 0.0, z: 0.0) { Constraints = pin });

      var elm1 = new BarElement(n1, n2);
      model.Elements.Add(elm1);

      double height = 200;
      double width = 50;
      double E = 7900; 
      var section = new UniformGeometric1DSection(SectionGenerator.GetRectangularSection(height, width));
      BaseMaterial material = UniformIsotropicMaterial.CreateFromYoungPoisson(E, 1);

      elm1.Section = section;
      elm1.Material = material;

      var u1 = new UniformLoad(LoadCase.DefaultLoadCase, new Vector(0, 0, 1), -3, CoordinationSystem.Local);
      elm1.Loads.Add(u1);

      model.Solve_MPC();

      double x;
      Force reaction1 = n1.GetSupportReaction();
      x = reaction1.Fz; //15000 = 3*10000/2 -> correct
      x = reaction1.My; // 0 -> correct

      Force f1_internal = elm1.GetInternalForceAt(-1);//-1 is start
      x = f1_internal.Fz; //bug: 0 should be -15000
      x = f1_internal.My; //bug: 25000000 should be 0, bug?
    }

**Comment by epsi1on** [comment]
Hi there.
You are right, there was bug in code and i've fixed that. But please note that you should use ``GetExactInternalForce()`` instead of ``GetInternalForce()``.

``GetInternalForce()`` do not see any effect of element body forces. in this example the uniform load. But it see the equivalent nodal loads of element's body loads. but ``GetExactInternalForce()`` will take the body loads into account.

I'll write a note about difference between ``GetExactInternalForce()`` and ``GetInternalForce()`` as soon as i can.

Thanks

**Comment by epsi1on** [comment]
can you please check and let me know if problem still exists?
